// src/app/blog/[slug]/page.tsx
// Prerender every published article at build time (ISR keeps them fresh).
// This route must be statically generated — a Dynamic (ƒ) route streams its
// shell, which locks the HTTP status at 200 and turns notFound() into a
// soft-404. As an SSG route, missing slugs return a real 404 status.
//
// NEWLY PUBLISHED BLOGS: slugs that were not prerendered at build time are
// rendered ON DEMAND (ISR). To keep those on-demand renders from 500-ing while
// Firestore is slow/cold on Vercel:
//   1. `dynamicParams = true` explicitly allows on-demand rendering of uncached
//      slugs (instead of rejecting them).
//   2. Every Firestore query is wrapped in a strict timeout guard, so a lagging
//      or hung query settles quickly.
//   3. A failed/timed-out fetch returns `null`, which becomes a graceful
//      notFound() — never an unhandled Server Component crash.

export const dynamicParams = true; // allow dynamic rendering for uncached slugs
export const revalidate = 60;

import { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { collection, query, where, getDocs, limit, orderBy } from "firebase/firestore";
import ReactMarkdown from "react-markdown";
import { Calendar, ArrowLeft, ChevronRight, BookOpen } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { db } from "@/lib/firebase";
import { Category, getCategoryBreadcrumbs } from "@/lib/blog-helpers";
import { BlogPost } from "@/components/blog/BlogCard";
import { computeArticleSplit, type ArticleSplitResult } from "@/lib/articleBanner";
import SupportBanner from "@/components/support/SupportBanner";
// VIEW COUNTER TEMPORARILY DISABLED (stabilize SSR on Vercel)
// import ArticleViewTracker from "@/components/blog/ArticleViewTracker";
// VIEW COUNTER TEMPORARILY DISABLED (stabilize SSR on Vercel)
// import { formatBengaliNumber } from "@/lib/formatBengaliNumber";

interface BlogDetailsPageProps {
  params: Promise<{ slug: string }>;
}

/**
 * Hard deadline for a single Firestore query. On cold serverless starts or
 * during on-demand (ISR) route resolution a hung query would otherwise hold the
 * render open until Vercel's function timeout → HTTP 500. Racing the query
 * against this timer guarantees the render always settles.
 */
const DB_TIMEOUT_MS = Number(process.env.BLOG_DB_TIMEOUT_MS ?? 8000);

function withTimeout<T>(promise: Promise<T>, ms: number = DB_TIMEOUT_MS): Promise<T> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  const deadline = new Promise<never>((_, reject) => {
    timer = setTimeout(
      () => reject(new Error(`Firestore query timed out after ${ms}ms`)),
      ms
    );
  });
  return Promise.race([promise, deadline]).finally(() => {
    if (timer) clearTimeout(timer);
  });
}

// Fetch Blog post helper
async function fetchBlogPost(rawSlug: string): Promise<BlogPost | null> {
  if (!rawSlug) return null;

  // Slugs are generated by `generateSlug` (lowercase, hyphenated). Normalise the
  // URL value so casing/encoding differences can never crash the route — the
  // worst case is a clean 404, never a 500.
  let slug = "";
  try {
    slug = decodeURIComponent(rawSlug).trim();
  } catch {
    slug = String(rawSlug).trim();
  }
  if (!slug) return null;

  const buildQuery = (value: string) =>
    query(
      collection(db, "blogs"),
      where("slug", "==", value),
      where("status", "==", "published"),
      limit(1)
    );

  try {
    let snap = await withTimeout(getDocs(buildQuery(slug)));

    // Second chance: tolerate a differently-cased slug instead of failing.
    if (snap.empty && slug !== slug.toLowerCase()) {
      snap = await withTimeout(getDocs(buildQuery(slug.toLowerCase())));
    }

    if (snap.empty) return null;
    const docEl = snap.docs[0];
    const data = docEl.data();
    return {
      id: docEl.id,
      title: data.title ?? "",
      slug: data.slug ?? slug,
      excerpt: data.excerpt ?? "",
      content: data.content ?? "",
      contentHtml: data.contentHtml ?? "",
      contentJson: data.contentJson ?? null,
      coverImage: data.coverImage ?? "",
      categoryIds: Array.isArray(data.categoryIds) ? data.categoryIds : [],
      status: data.status || "published",
      views: typeof data.views === "number" ? data.views : 0,
      createdAt: data.createdAt,
    } as BlogPost;
  } catch (err) {
    // Timeout / network / permission error on an on-demand request → return
    // null so the page renders a graceful notFound() instead of a 500.
    console.error("Error fetching dynamic blog post on Vercel:", err);
    return null;
  }
}

// Fetch Categories Helper
async function fetchAllCategories(): Promise<Category[]> {
  try {
    const snap = await withTimeout(
      getDocs(query(collection(db, "categories"), orderBy("createdAt", "asc")))
    );
    return snap.docs.map((docEl) => {
      const data = docEl.data();
      return {
        id: docEl.id,
        name: data.name,
        slug: data.slug,
        parentId: data.parentId || null,
        level: data.level || 1,
      };
    });
  } catch (err) {
    console.error("Error loading categories:", err);
    return [];
  }
}

// Fetch Related Blogs Helper
async function fetchRelatedBlogs(categoryId: string, currentBlogId: string): Promise<BlogPost[]> {
  try {
    const q = query(
      collection(db, "blogs"),
      where("status", "==", "published"),
      where("categoryIds", "array-contains", categoryId),
      limit(4)
    );
    const snap = await withTimeout(getDocs(q));
    const list: BlogPost[] = [];
    snap.docs.forEach((docEl) => {
      if (docEl.id !== currentBlogId && list.length < 3) {
        const data = docEl.data();
        list.push({
          id: docEl.id,
          title: data.title,
          slug: data.slug,
          excerpt: data.excerpt,
          coverImage: data.coverImage,
          categoryIds: data.categoryIds || [],
          status: data.status,
          views: data.views || 0,
          createdAt: data.createdAt,
        } as BlogPost);
      }
    });
    return list;
  } catch (err) {
    console.error("Error loading related blogs: ", err);
    return [];
  }
}

// Prerender the slugs of all currently published posts at build time.
// Slugs come straight from the Firestore `slug` field, so they always match the
// exact casing/hyphenation used by `generateSlug` when the post was saved.
// A failure/timeout here must never break the build — we return [] and fall back
// to on-demand rendering (dynamicParams = true) instead.
export async function generateStaticParams(): Promise<{ slug: string }[]> {
  try {
    const snap = await withTimeout(
      getDocs(
        query(collection(db, "blogs"), where("status", "==", "published"), limit(1000))
      ),
      15000 // build-time window: a bit more headroom than the per-request guard
    );
    return snap.docs
      .map((docEl) => docEl.data()?.slug)
      .filter((slug): slug is string => typeof slug === "string" && slug.trim().length > 0)
      .map((slug) => ({ slug }));
  } catch (err) {
    console.error("generateStaticParams (blog [slug]) failed:", err);
    return [];
  }
}

// Next.js Dynamic SEO Metadata Generator
// Wrapped in try/catch + optional chaining: a metadata failure must never turn
// into a 500 for the whole route.
export async function generateMetadata({ params }: BlogDetailsPageProps): Promise<Metadata> {
  try {
    const { slug } = await params;
    const post = await fetchBlogPost(slug);

    if (!post) {
      return {
        title: "Blog Not Found | BCS Spark",
      };
    }

    const seoTitle = `${post.title || "ব্লগ"} | BCS Spark Blog`;
    const seoDescription =
      post.excerpt || `${post.title || "এই ব্লগ"} সম্পর্কে বিস্তারিত জানুন BCS Spark ব্লগে।`;

    const ogImages = post.coverImage ? [{ url: post.coverImage }] : undefined;
    const publishedTime = post.createdAt?.toDate ? post.createdAt.toDate().toISOString() : undefined;

    return {
      title: seoTitle,
      description: seoDescription,
      openGraph: {
        title: seoTitle,
        description: seoDescription,
        type: "article",
        publishedTime,
        images: ogImages,
      },
    };
  } catch (err) {
    console.error("generateMetadata (blog [slug]) failed:", err);
    return {
      title: "BCS Spark Blog",
    };
  }
}

// TEMPORARY DIAGNOSTIC WRAPPER — captures the EXACT runtime crash in Vercel
// Function Logs (message + full stack + source line) for the on-demand 500.
// Once the root cause is confirmed and fixed, this wrapper can be removed.
// NOTE: notFound() throws a special Next.js error; rethrowing it preserves its
// internal `digest`, so a missing post still renders a real 404 — never a 500.
export default async function BlogDetailsPage({ params }: BlogDetailsPageProps) {
  try {
    return await renderBlogDetailsPage(params);
  } catch (err: any) {
    console.error(
      "CRITICAL VERCEL SSR CRASH IN BLOG PAGE:",
      err?.stack || err?.message || err
    );
    throw err;
  }
}

async function renderBlogDetailsPage(params: BlogDetailsPageProps["params"]) {
  const { slug } = await params;
  console.log("Rendering dynamic blog page for slug:", slug);
  const post = await fetchBlogPost(slug);

  // Missing / unpublished / deleted post → a real 404 (never a 500).
  // The styled UI lives in ./not-found.tsx, rendered by notFound().
  if (!post) {
    notFound();
  }

  // Fetch category lists and build breadcrumbs — a category lookup failure must
  // never take the whole article down.
  let flatCategories: Category[] = [];
  try {
    flatCategories = await fetchAllCategories();
  } catch (err) {
    console.error("Blog page: failed to load categories:", err);
  }

  const primaryCategoryId =
    Array.isArray(post.categoryIds) && post.categoryIds.length > 0
      ? post.categoryIds[post.categoryIds.length - 1]
      : null;
  const breadcrumbs = getCategoryBreadcrumbs(primaryCategoryId, flatCategories);

  // Fetch related posts (non-critical)
  let relatedPosts: BlogPost[] = [];
  if (primaryCategoryId) {
    try {
      relatedPosts = await fetchRelatedBlogs(primaryCategoryId, post.id);
    } catch (err) {
      console.error("Blog page: failed to load related posts:", err);
    }
  }

  const formatDate = (timestamp: any) => {
    if (!timestamp) return "";
    const date = timestamp.toDate ? timestamp.toDate() : new Date(timestamp);
    return date.toLocaleDateString("bn-BD", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
  };

  // Predefined custom Markdown styled components matching the application
  const markdownComponents = {
    h1: (props: any) => <h1 className="text-2xl sm:text-3xl font-bold mt-6 mb-4 text-gray-900 border-b pb-2" {...props} />,
    h2: (props: any) => <h2 className="text-xl sm:text-2xl font-bold mt-5 mb-3 text-gray-900" {...props} />,
    h3: (props: any) => <h3 className="text-lg sm:text-xl font-semibold mt-4 mb-2 text-gray-900" {...props} />,
    p: (props: any) => <p className="mb-4 text-gray-700 leading-relaxed text-base sm:text-lg" {...props} />,
    ul: (props: any) => <ul className="list-disc pl-6 mb-4 space-y-2 text-gray-700 text-base sm:text-lg" {...props} />,
    ol: (props: any) => <ol className="list-decimal pl-6 mb-4 space-y-2 text-gray-700 text-base sm:text-lg" {...props} />,
    li: (props: any) => <li className="mb-0.5" {...props} />,
    a: (props: any) => <a className="text-blue-600 hover:underline hover:text-blue-800 font-semibold break-all" target="_blank" rel="noopener noreferrer" {...props} />,
    blockquote: (props: any) => (
      <blockquote className="border-l-4 border-blue-500 pl-4 italic text-gray-600 my-5 bg-blue-50/50 py-3 pr-2 rounded-r text-base sm:text-lg" {...props} />
    ),
    code: ({ node, className, children, ...props }: any) => {
      const match = /language-(\w+)/.exec(className || "");
      const isInline = !match;
      return isInline ? (
        <code className="bg-gray-100 text-pink-600 px-1.5 py-0.5 rounded text-sm font-mono font-semibold" {...props}>
          {children}
        </code>
      ) : (
        <pre className="bg-gray-900 text-gray-100 p-4 rounded-xl overflow-x-auto text-xs sm:text-sm font-mono my-4 shadow-inner">
          <code className={className} {...props}>
            {children}
          </code>
        </pre>
      );
    },
    table: (props: any) => (
      <div className="overflow-x-auto my-6 rounded-lg border border-gray-100 shadow-sm">
        <table className="min-w-full divide-y divide-gray-200" {...props} />
      </div>
    ),
    th: (props: any) => <th className="bg-gray-50 px-4 py-3.5 text-left text-xs font-semibold text-gray-700 uppercase tracking-wider border-b" {...props} />,
    td: (props: any) => <td className="px-4 py-3 text-sm text-gray-600 border-b" {...props} />,
    img: (props: any) => <img className="rounded-xl max-h-96 mx-auto object-cover my-6 shadow-md" {...props} />,
  };

  // Compute where to place the mid-article banner (safe top-level block boundary).
  // `before`/`after` are re-usable for whichever pipeline renders the body below.
  // `computeArticleSplit` parses HTML with jsdom (a transitive dependency) and
  // can throw on unusual markup — if it fails we still render the full body,
  // just without the mid banner, instead of a 500.
  let articleSplit: ArticleSplitResult = {
    before: post.contentHtml || post.content || null,
    after: null,
    showMiddle: false,
  };
  const computed = await computeArticleSplit({ html: post.contentHtml, markdown: post.content });
  if (computed.before || computed.after) articleSplit = computed;
  const hasHtmlBody = Boolean(post.contentHtml);

  return (
    <>
      <Navbar />
      {/* VIEW COUNTER TEMPORARILY DISABLED (stabilize SSR on Vercel) */}
      {/* <ArticleViewTracker slug={post.slug} /> */}

      <main className="flex-1 bg-brand-bg py-8 font-sans">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 space-y-6">
          
          {/* Back navigation & Breadcrumbs */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-sm">
            <Link
              href="/blog"
              className="inline-flex items-center gap-2 text-gray-600 hover:text-blue-600 font-semibold transition-colors group"
            >
              <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-0.5" />
              <span>সব ব্লগ তালিকা</span>
            </Link>

            {breadcrumbs.length > 0 && (
              <div className="flex items-center flex-wrap gap-1 text-gray-500">
                <span className="hover:text-blue-600">
                  <Link href="/blog">ব্লগ</Link>
                </span>
                {breadcrumbs.map((crumb) => (
                  <span key={crumb.id} className="flex items-center gap-1">
                    <ChevronRight className="h-3 w-3 text-gray-300 shrink-0" />
                    <Link
                      href={`/blog/category/${crumb.slug}`}
                      className="hover:text-blue-600 font-medium truncate max-w-[120px]"
                    >
                      {crumb.name}
                    </Link>
                  </span>
                ))}
              </div>
            )}
          </div>

          {/* Main Article Container */}
          <article className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden p-6 sm:p-8 space-y-6">
            
            {/* Header elements */}
            <div className="space-y-4">
              <h1 className="text-2xl sm:text-4xl font-extrabold text-gray-900 leading-tight">
                {post.title}
              </h1>

              {/* Excerpt if present */}
              {post.excerpt && (
                <p className="text-gray-600 text-base sm:text-lg border-l-4 border-gray-200 pl-3.5 leading-relaxed">
                  {post.excerpt}
                </p>
              )}

              {/* Meta stats */}
              <div className="flex items-center gap-4 text-xs sm:text-sm text-gray-500 border-y border-gray-50 py-3 shrink-0">
                <div className="flex items-center gap-1.5">
                  <Calendar className="h-4 w-4 text-gray-400" />
                  <span>পাবলিশড: {formatDate(post.createdAt)}</span>
                </div>
                {/* VIEW COUNTER TEMPORARILY DISABLED (stabilize SSR on Vercel) */}
                {/* <div className="flex items-center gap-1.5">
                  <Eye className="h-4 w-4 text-gray-400" />
                  <span>{formatBengaliNumber(post.views)} বার পঠিত</span>
                </div> */}
              </div>
            </div>

            {/* Cover Image */}
            {post.coverImage && (
              <div className="aspect-video w-full rounded-2xl overflow-hidden bg-gray-50 border border-gray-100">
                <img
                  src={post.coverImage}
                  alt={post.title}
                  className="w-full h-full object-cover"
                />
              </div>
            )}

            {/* Blog body — rich HTML (primary) or legacy markdown fallback */}
            <div className="prose prose-lg max-w-none pt-2 ">
              {articleSplit.before ? (
                hasHtmlBody ? (
                  <div dangerouslySetInnerHTML={{ __html: articleSplit.before }} />
                ) : (
                  <ReactMarkdown components={markdownComponents}>{articleSplit.before}</ReactMarkdown>
                )
              ) : null}

              {/* Mid-article support banner (only on medium/long posts) */}
              {articleSplit.showMiddle && (
                <div className="not-prose mx-auto my-8 md:my-10 lg:my-12 w-full max-w-[728px]">
                  <SupportBanner />
                </div>
              )}

              {articleSplit.after ? (
                hasHtmlBody ? (
                  <div dangerouslySetInnerHTML={{ __html: articleSplit.after }} />
                ) : (
                  <ReactMarkdown components={markdownComponents}>{articleSplit.after}</ReactMarkdown>
                )
              ) : null}
            </div>
          </article>

          {/* End-of-article support banner — after the body, before recommendations */}
          <div className="mx-auto w-full max-w-[728px]">
            <SupportBanner />
          </div>

          {/* Related Articles Panel */}
          {relatedPosts.length > 0 && (
            <div className="space-y-4 pt-6 border-t border-gray-200">
              <h2 className="text-xl font-bold text-gray-900 flex items-center gap-2">
                <BookOpen className="h-5 w-5 text-blue-600" />
                <span>সম্পর্কিত অন্যান্য ব্লগ</span>
              </h2>

              <div className="grid gap-6 sm:grid-cols-3">
                {relatedPosts.map((rPost) => (
                  <div
                    key={rPost.id}
                    className="bg-white rounded-xl border border-gray-100 shadow-sm p-4 hover:shadow-md transition flex flex-col justify-between"
                  >
                    <div className="space-y-2">
                      {rPost.coverImage && (
                        <Link href={`/blog/${rPost.slug}`} className="block aspect-video rounded-lg overflow-hidden bg-gray-50 mb-2">
                          <img
                            src={rPost.coverImage}
                            alt={rPost.title}
                            className="w-full h-full object-cover hover:scale-105 transition-transform duration-300"
                          />
                        </Link>
                      )}
                      <Link
                        href={`/blog/${rPost.slug}`}
                        className="font-bold text-gray-900 hover:text-blue-600 transition-colors line-clamp-2 text-sm leading-snug"
                      >
                        {rPost.title}
                      </Link>
                    </div>
                    <span className="text-[10px] text-gray-400 mt-3 block">{formatDate(rPost.createdAt)}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </main>

      <Footer />
    </>
  );
}
